version: "3"
services:
  mongo:
    image: mongo
    container_name: workspace_mongo
    ports:
      - 27017:27017
    logging:
      driver: none

  redis:
    image: redis
    container_name: workspace_cache
    ports:
      - 6379:6379
    logging:
      driver: none

  api:
    container_name: workspace_api
    restart: always
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - 3030:3030
      - 9229:9229
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
      - redis
    
  socket:
    container_name: workspace_socket
    restart: always
    build:
      context: .
      dockerfile: ./packages/socket/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
      - redis
      - api
    
  client:
    container_name: workspace_client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    links:
      - api
      - socket
