name: Client Workflow

on:
  push:
    tags:
      - '*@wordic/client@*'

jobs:
  build:
    name: Deploy API

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}