name: Client Workflow

on:
  push:
    tags:
      - '*@wordic/client@*'

jobs:
  build:
    name: Deploy Client

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/client/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      # - uses: Shopify/upload-to-release
      #   with:
      #     name: my-artifact
      #     path: packages/client/build/
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     content-type: text/plain # Optional