name: Tag Workflow

on:
  push:
    # Sequence of patterns matched against refs/heads
    # branches:    
    #   - master         # Push events on master branch
    #   - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # Sequence of patterns matched against refs/tags
    tags:        
      - '**/*@wordic/api@*'

jobs:
  build:
    name: Deploy Tag

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}