name: Tag Workflow

on:
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased

jobs:
  build:
    name: Deploy Tag

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}