name: Test Workflow

on:
  push:
    tags:
      - '**/*'

jobs:
  build:
    name: Deploy Tag

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/@wordic/', '')
      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}

      - name: Echo
        run: echo ${{ github.ref }}

      - name: Set Vars
        id: vars
        run: |

          [[ "${{ github.ref }}" ==  *"beta"* ]] && ENV_TYPE="SE" || ENV_TYPE="PROD"

          echo "${{ github.ref }}"
          echo $ENV_TYPE

          echo ::set-output name=env_type::$ENV_TYPE

      - name: Build
        run: |
          echo ${{ steps.vars.outputs.env_type }}

          . ./tools/setup-env.sh ${{ steps.vars.outputs.env_type }} INTERCOM_APP_ID

          echo "${{ github.ref }}"

          echo $INTERCOM_APP_ID
        env:
          INTERCOM_APP_ID_PROD: "proda"
          INTERCOM_APP_ID_SE: "asdiluhalsiudgalsdhlajsdhlajsds"
          